name = "aoc"
description = "Library for Advent of Code (AoC)"
version = "0.1.1-dev"

authors = ["Daniel Larraz"]
maintainers = ["Daniel Larraz <daniel-larraz@users.noreply.github.com>"]
maintainers-logins = ["daniel-larraz"]

[build-switches]
"*".ada_version = "Ada2022"

[[depends-on]]
gnatprove = "^15.1.0"
